name: Security Register CD

on:
  #pull_request:
  #  branches:
  #   - master
  #  types:
  #    - closed
  push:
    branches:

jobs:
  deploy:
   # if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: miisteuhdiack/secure-angular-app:preprod

    - name: Deploy App
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script:  |
          docker stop miisteuhdiack/secure-angular-app:preprod || true
          docker image rm miisteuhdiack/secure-angular-app:preprod
          docker pull miisteuhdiack/secure-angular-app:preprod
          docker run -p 80:80 -d miisteuhdiack/secure-angular-app:preprod
