name: Angular Secure App CI

on:
  push:
    branches:
    - '**'
    - '!master'

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
    - uses: actions/checkout@v3
    - name: Setup NodeJs
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        cache-dependency-path: './package-lock.json'

    - name: Install dependencies
      run: npm ci

    - name: Run SCA and Generate report
      run: |
         npm audit --json > npm-audit.json || true
         npx npm-audit-html -i npm-audit.json

    - name: Archive audit report
      uses: actions/upload-artifact@v3
      with:
          name: npm-audit-report
          path: ./npm-audit.html


