name: Angular Secure App CI

on:
  push:
    branches:
    - '**'
    - '!master'

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
    - uses: actions/checkout@v3
    - name: Setup NodeJs
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        cache-dependency-path: './package-lock.json'

    - name: Install dependencies
      run: npm ci

    - name: Run SCA
      run: npm audit --json > npm-audit.json || true

    - name: Generate  udit Report
      run: npx npm-audit-html -i npm-audit.json

    - name: Display audit report
      run: ls $GITHUB_WORKSPACE || true

    - name: Archive audit Report
      uses: actions/upload-artifact@v3
      with:
          name: npm-audit-report
          path: $GITHUB_WORKSPACE/secure-app/angular/npm-audit.html


