name: Security Register CD

on:
  #pull_request:
  #  branches:
  #   - master
  #  types:
  #    - closed
  push:
    branches:
      - 'master'

jobs:
  deploy:
   # if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: miisteuhdiack/secure-angular-app:preprod

    - name: Deploy App
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script:  |
          docker stop miisteuhdiack/secure-angular-app:preprod || true
          docker image rm miisteuhdiack/secure-angular-app:preprod
          docker pull miisteuhdiack/secure-angular-app:preprod
          docker run -p 80:80 -d miisteuhdiack/secure-angular-app:preprod

  dast:
    needs: deploy

    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run DAST
        run: |
          docker run -t owasp/zap2docker-stable zap-baseline.py -t http://51.83.71.17/" || true



